/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package agent_bancaire;

import GUI.Connexion;
import Protocol.Pull;
import Protocol.Push;
import java.awt.Color;
import java.awt.Component;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import static java.lang.System.exit;
import java.net.Socket;
import java.util.List;
import java.util.ArrayList;
import java.util.Date;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.crypto.SealedObject;
import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.table.DefaultTableModel;
import m18.kerberos.as.ASReply;
import m18.kerberos.as.ASRequest;
import m18.kerberos.as.KcTGS;
import m18.kerberos.tgs.AuthenticatorTGS;
import m18.kerberos.tgs.TGSReply;
import m18.kerberos.tgs.TGSRequest;
import m18.kerberos.tgs.TicketCS;

/**
 *
 * @author Thibault
 */
public class Agent_Bancaire extends javax.swing.JFrame
{
    
    private Socket cSock1;
    private ObjectInputStream ois1;
    private ObjectOutputStream oos1;
    private int PORT1;
    private String IP1;
    private String IPAS;
    private int PORTAS;
    private String IPTGS;
    private int PORTTGS;
    
    private KcTGS KCTGS;
    
    private TicketCS Ticket;
    private SealedObject Authentificateur;
    
    private SecretKey KCS;
    private AuthenticatorTGS auth;
    
    public Agent_Bancaire()
    {
        initComponents();
        
        // <editor-fold defaultstate="collapsed" desc="Init Properties 1">
        /*
        try
        {
        Properties prop = new Properties();
        FileOutputStream fos = new FileOutputStream("Agent_Bancaire_1.properties");
        prop.setProperty("port", "7373");
        prop.setProperty("ip", "127.0.0.1");
        prop.setProperty("ipAS", "10.43.14.13");
        prop.setProperty("portAS", "3800");
        prop.setProperty("ipTGS", "127.0.0.1");
        prop.setProperty("portTGS", "3838");
        
        prop.store(fos, null);
        }
        catch(Exception ex){}
        */
        // </editor-fold>
        
        // <editor-fold defaultstate="collapsed" desc="Load Properties 1">
        try
        {
            Properties prop = new Properties();
            FileInputStream fis = new FileInputStream("Agent_Bancaire_1.properties");
            prop.load(fis);
            
            PORT1 = Integer.parseInt(prop.getProperty("port", "7373"));
            IP1 = prop.getProperty("ip", "127.0.0.1");
            PORTAS = Integer.parseInt(prop.getProperty("portAS", "3800"));
            IPAS = prop.getProperty("ipAS", "127.0.0.1");
            PORTTGS = Integer.parseInt(prop.getProperty("portTGS", "3838"));
            IPTGS = prop.getProperty("ipTGS", "127.0.0.1");
            
            
            fis.close();
        } catch (IOException ex)
        {
            Logger.getLogger(Agent_Bancaire.class.getName()).log(Level.SEVERE, null, ex);
        }
        // </editor-fold>
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        TPPrinc = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        p1Ctrl = new javax.swing.JPanel();
        b1Connexion = new javax.swing.JButton();
        Status1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tf1Banque = new javax.swing.JTextField();
        b1Valider = new javax.swing.JButton();
        b1Recherche = new javax.swing.JButton();
        cb1Valide = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tOperations = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        p1Ctrl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contrôles", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        b1Connexion.setText("Connexion");
        b1Connexion.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                b1ConnexionActionPerformed(evt);
            }
        });

        Status1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Status1.setOpaque(true);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Banque");
        jLabel1.setEnabled(false);

        tf1Banque.setEnabled(false);

        b1Valider.setText("Valider");
        b1Valider.setEnabled(false);
        b1Valider.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                b1ValiderActionPerformed(evt);
            }
        });

        b1Recherche.setText("Recherche");
        b1Recherche.setEnabled(false);
        b1Recherche.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                b1RechercheActionPerformed(evt);
            }
        });

        cb1Valide.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Any", "True", "False" }));
        cb1Valide.setEnabled(false);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Validé");
        jLabel2.setEnabled(false);

        javax.swing.GroupLayout p1CtrlLayout = new javax.swing.GroupLayout(p1Ctrl);
        p1Ctrl.setLayout(p1CtrlLayout);
        p1CtrlLayout.setHorizontalGroup(
            p1CtrlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1CtrlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p1CtrlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b1Connexion, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p1CtrlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(p1CtrlLayout.createSequentialGroup()
                        .addComponent(tf1Banque, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb1Valide, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Status1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p1CtrlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b1Valider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b1Recherche, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        p1CtrlLayout.setVerticalGroup(
            p1CtrlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1CtrlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p1CtrlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p1CtrlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(b1Connexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Status1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(b1Recherche))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p1CtrlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addGroup(p1CtrlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf1Banque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b1Valider)
                        .addComponent(cb1Valide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        tOperations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Id", "Banque", "Type", "Montant", "Validé"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tOperations);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p1Ctrl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(p1Ctrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        TPPrinc.addTab("Bank Server", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 778, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );

        TPPrinc.addTab("Data Server", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TPPrinc)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TPPrinc)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ConnexionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_b1ConnexionActionPerformed
    {//GEN-HEADEREND:event_b1ConnexionActionPerformed
        try
        {
            cSock1 = new Socket(IPAS, PORTAS);
            ois1 = new ObjectInputStream(cSock1.getInputStream());
            oos1 = new ObjectOutputStream(cSock1.getOutputStream());
            
            Connexion co = new Connexion(this, true);
            co.setVisible(true);
            
            String pseudo = co.getPseudo();
            String passwd = co.getPasswd();
            while(passwd.length() < 8)
                passwd += passwd;
            passwd = passwd.substring(0, 8);
            
            ASRequest asReq = new ASRequest("INITIAL_REQUEST", pseudo, passwd, "127.0.0.1", "TGS");
            oos1.writeObject(asReq);
            
            // Génération KC
            SecretKey KC = new SecretKeySpec(passwd.getBytes(), "DES");
            Cipher cipher = Cipher.getInstance("DES/ECB/PKCS5Padding");
            cipher.init(Cipher.DECRYPT_MODE, KC);
            
            // Récupération clé de session
            ASReply asRep = (ASReply)ois1.readObject();
            KCTGS = (KcTGS) asRep.getKCTGS().getObject(cipher);
            
            // Création authenticator
            auth = new AuthenticatorTGS();
            auth.setClientName(pseudo);
            auth.setCurrentTime(new Date());
            auth.setChecksum(auth.getClientName().hashCode());
            
            cipher = Cipher.getInstance("DES/ECB/PKCS5Padding");
            cipher.init(Cipher.ENCRYPT_MODE, KCTGS.getKCTGSSessionKey());
            SealedObject soAuth = new SealedObject(auth, cipher);
            
            // Création TGS Request
            TGSRequest TGSreq = new TGSRequest();
            TGSreq.setService(IP1);
            TGSreq.setTicket(asRep.getTicket());
            TGSreq.setAuthenticator(soAuth);
            
            // Changement socket
            cSock1 = new Socket(IPTGS, PORTTGS);
            ois1 = new ObjectInputStream(cSock1.getInputStream());
            oos1 = new ObjectOutputStream(cSock1.getOutputStream());
            
            // Envoi TGS Request
            oos1.writeObject(TGSreq);
            
            // TGS Reply
            TGSReply TGSrep = (TGSReply)ois1.readObject();
            System.out.println("TGS Reply reçu !!");
            
            // Sauvegarde Authentificateur et Ticket
            Ticket = TGSrep.getTicket();
            cipher.init(Cipher.DECRYPT_MODE, KCTGS.getKCTGSSessionKey());
            KCS = (SecretKey) TGSrep.getKCSkey().getObject(cipher);
            cipher.init(Cipher.ENCRYPT_MODE, KCS);
            Authentificateur = new SealedObject(auth, cipher);
            System.out.println("Fin Kerberos");
            
            cSock1.close();
            cSock1 = new Socket(IP1, PORT1);
            ois1 = new ObjectInputStream(cSock1.getInputStream());
            oos1 = new ObjectOutputStream(cSock1.getOutputStream());                        
            
            for (Component c : this.p1Ctrl.getComponents())
            {
                c.setEnabled(true);
            }
            this.b1Connexion.setEnabled(false);
            
        } catch (Exception ex)
        {
            Logger.getLogger(Agent_Bancaire.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b1ConnexionActionPerformed

    private void b1ValiderActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_b1ValiderActionPerformed
    {//GEN-HEADEREND:event_b1ValiderActionPerformed
        try
        {
            int[] indices = this.tOperations.getSelectedRows();
            ArrayList<String> ids = new ArrayList<>();
            
            for (int ind : indices)
                ids.add(this.tOperations.getValueAt(ind, 0).toString());
            
            Pull pull = new Pull();
            pull.setAuthenticator(this.Authentificateur);
            pull.setTicket(this.Ticket);
            pull.setName("validation");
            pull.setIds(ids);
            
            oos1.writeObject(pull);
            
            Push push = (Push)ois1.readObject();
            SealedObject so = push.getTimestamp();
            Cipher c = Cipher.getInstance("DES/ECB/PKCS5Padding");
            c.init(Cipher.DECRYPT_MODE, KCS);
            Date timestamp = (Date)so.getObject(c);
            if(timestamp == auth.getCurrentTime())
                System.out.println("Serveur authentifié");
            
            if(push.getName().equalsIgnoreCase("validOK"))
            {
                this.Status1.setText("Validation réussie");
                this.Status1.setBackground(Color.green);
            }
            else
            {
                this.Status1.setText("Echec validation");
                this.Status1.setBackground(Color.red);
            }
        }
        catch (IOException | ClassNotFoundException ex)
        {
            this.Status1.setText("Echec validation");
            this.Status1.setBackground(Color.red);
            Logger.getLogger(Agent_Bancaire.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex)
        {
            Logger.getLogger(Agent_Bancaire.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b1ValiderActionPerformed

    private void b1RechercheActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_b1RechercheActionPerformed
    {//GEN-HEADEREND:event_b1RechercheActionPerformed
        try
        {
            DefaultTableModel dm = (DefaultTableModel) this.tOperations.getModel();
            int rowCount = dm.getRowCount();
            for (int i = rowCount - 1; i >= 0; i--)
            {
                dm.removeRow(i);
            }
            
            Pull pull = new Pull();
            pull.setAuthenticator(this.Authentificateur);
            pull.setTicket(this.Ticket);
            pull.setName("recherche");
            pull.setBanque(this.tf1Banque.getText());
            int choix = this.cb1Valide.getSelectedIndex();
            switch(choix)
            {
                case 0:
                    pull.setValide("any");
                    break;
                case 1:
                    pull.setValide("true");
                    break;
                case 2:
                    pull.setValide("false");
                    break;
            }
            oos1.writeObject(pull);
            
            Push push = (Push) ois1.readObject();
            SealedObject so = push.getTimestamp();
            Cipher c = Cipher.getInstance("DES/ECB/PKCS5Padding");
            c.init(Cipher.DECRYPT_MODE, KCS);
            Date timestamp = (Date)so.getObject(c);
            if(timestamp == auth.getCurrentTime())
                System.out.println("Serveur authentifié");
            
            DefaultTableModel dtm = (DefaultTableModel) this.tOperations.getModel();
            List<Object> list = null;
            for(int i = 0 ; i < push.getIds().size() ; i ++)
            {
                list = new ArrayList<>();
                list.add(push.getIds().get(i));
                list.add(push.getBanques().get(i));
                list.add(push.getTypes().get(i));
                list.add(push.getMontants().get(i));
                list.add(push.getValides().get(i));
                
                dtm.addRow(list.toArray());
            }
            this.tOperations.setModel(dtm);
            
            this.Status1.setText("Recherche réussie : " + dtm.getRowCount() + " résultats");
            this.Status1.setBackground(Color.green);
        }
        catch (IOException | ClassNotFoundException ex)
        {
            this.Status1.setText("Echec recherche");
            this.Status1.setBackground(Color.red);
            Logger.getLogger(Agent_Bancaire.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(Exception ex)
        {
            Logger.getLogger(Agent_Bancaire.class.getName()).log(Level.SEVERE, null, ex);            
        }
    }//GEN-LAST:event_b1RechercheActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        try
        {
            Pull pull = new Pull();
            pull.setAuthenticator(this.Authentificateur);
            pull.setTicket(this.Ticket);
            pull.setName("END");
            oos1.writeObject(pull);
            System.out.println("Closing");
            ois1.close();
            oos1.close();
            cSock1.close();
            exit(0);
        }
        catch (Exception ex)
        {
            exit(0);
        }
    }//GEN-LAST:event_formWindowClosing
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Agent_Bancaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Agent_Bancaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Agent_Bancaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Agent_Bancaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Agent_Bancaire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Status1;
    private javax.swing.JTabbedPane TPPrinc;
    private javax.swing.JButton b1Connexion;
    private javax.swing.JButton b1Recherche;
    private javax.swing.JButton b1Valider;
    private javax.swing.JComboBox cb1Valide;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel p1Ctrl;
    private javax.swing.JTable tOperations;
    private javax.swing.JTextField tf1Banque;
    // End of variables declaration//GEN-END:variables
}
