USE BD_CLIENTS;

DROP TABLE IF EXISTS COMPTES;
DROP TABLE IF EXISTS OPERATIONS;
DROP TABLE IF EXISTS CLIENTS;

CREATE TABLE CLIENTS
(
	IdClient INTEGER AUTO_INCREMENT,
    Email VARCHAR(254) UNIQUE,
    Nom VARCHAR(50),
	Prenom VARCHAR(50),
    Mdp VARCHAR(50),
    Adresse VARCHAR(200),
    CodePostal VARCHAR(4),
    Pays VARCHAR(50),
	CONSTRAINT CLIENTS$pk PRIMARY KEY(IdClient),
	CONSTRAINT CLIENTS$Email CHECK (Email IS NOT NULL),
	CONSTRAINT CLIENTS$Mdp CHECK (Mdp IS NOT NULL)
);

CREATE TABLE OPERATIONS
(
    IdOp INTEGER AUTO_INCREMENT,
    DateOp DATE,
    ClientID INTEGER NOT NULL,
	OperationID INTEGER NOT NULL,
	TypeOp VARCHAR(100),
	Traitee BOOLEAN,
	Montant FLOAT,
    CONSTRAINT OPERATIONS$pk PRIMARY KEY(IdOp),
	CONSTRAINT OPERATIONS$DateOp CHECK (DateOp IS NOT NULL),
	CONSTRAINT OPERATIONS$TypeOp CHECK (TypeOp IS NOT NULL),
	CONSTRAINT OPERATIONS$Montant CHECK (Montant IS NOT NULL),
	CONSTRAINT FOREIGN KEY(OperationID)REFERENCES OPERATIONS(OperationID),
	CONSTRAINT FOREIGN KEY(ClientID) REFERENCES CLIENTS(IdClient)
	
);

CREATE TABLE COMPTES
(
	IdCompte INTEGER AUTO_INCREMENT,
	NumCompte VARCHAR(200) UNIQUE,
	ClientID INTEGER NOT NULL,
	Fiable BOOLEAN,
	Montant FLOAT,
	CONSTRAINT COMPTES$pk PRIMARY KEY(IdCompte),
	CONSTRAINT COMPTES$Montant CHECK (Montant IS NOT NULL),
	CONSTRAINT COMPTES$NumCompte CHECK (NumCompte IS NOT NULL),
	CONSTRAINT FOREIGN KEY(ClientID) REFERENCES CLIENTS(IdClient)
);






